title:
    en: The document title (in en)
    vi: The document title (in vi)
summary:
    en: Summary about document content (in en)
    vi: Summary about document content (in vi)
icon: fas fa-file
file:
    en: index-en.md
    vi: index-vi.md
tags:
    en:
        - the
        - document
        - title
        - in
        - en
    vi:
        - the
        - document
        - title
        - in
        - vi
tc: 1683215751
tu: 1683215751
