title:
    en: Programming
    vi: Lập trình
description:
    en: "Unleashing the Power of Code: A Journey into the World of Programming."
    vi: "Khám phá sức mạnh của mã nguồn: Chuyến đi vào thế giới lập trình."
icon: fas fa-code
