name: MyPersonalNotes
description:
    en: Capturing my learning adventure as I explore the world of tech and programming.
    vi: Những dấu chân trên hành trình học tập, khám phá thế giới công nghệ và lập trình.
languages:
    default: en
    en: English
    vi: Tiếng Việt
icon: fas fa-blog
contacts:
    email: btnguyen2k (at) gmail (dot) com
    github: https://github.com/btnguyen2k/
    linkedin: https://www.linkedin.com/in/btnguyen2k/
    website: https://github.com/btnguyen2k/
tags:
    build: ${build_datetime}
    vi_only: "This post content is available only in Vietnamese language."
tagalias:
    en:
        token: [tokens]
        vuejs: [vue, vue3]
    vi:
        vuejs: [vue, vue3]
mode: blog
author:
    name: Thanh Nguyen
    avatar: //www.gravatar.com/avatar/9d6ee977a36db465f103ea5c0e4b859c
