title:
    en: Contact
    vi: Liên hệ
summary:
    en: Contact information
    vi: Thông tin liên lệ
icon: fas fa-address-card
page: contact
style: contact
file:
    en: index-en.md
    vi: index-vi.md
tc: 1683787927
tu: 1683787927
