title:
    en: Host your website on Azure, for free
    vi: Đưa trang web của bạn lên Azure, miễn phí
summary:
    en: This post demonstrates how you can host your website on Azure at no cost.
    vi: Bài viết hướng dẫn bạn đưa trang web lên Azure hoàn toàn miễn phí.
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    en: index-en.md
    vi: index-vi.md
tags:
    en: [azure, free hosting]
    vi: [azure, free hosting, miễn phí]
tc: 1684237260
tu: 1684237260
