title:
    en: DevOps
    vi: DevOps
description:
    en: "Embrace the power of collaboration: Streamline, Automate, Deliver."
    vi: "Sức mạnh từ sự hợp tác: Tối ưu hóa, Tự động hóa, Triển khai."
icon: fas fa-screwdriver-wrench
