title:
    en: Privacy Statement
    vi: Tuyên bố Quyền riêng tư
summary:
    en: "Privacy Statement (Last updated: 2023-07-03)"
    vi: "Tuyên bố Quyền riêng tư (Cập nhật lần cuối: 2023-07-03)"
icon: fas fa-key
page: privacy-policy
style:
file:
    en: index-en.md
    vi: index-vi.md
tc: 1688350842
tu: 1688350842
