title:
    en: Programming
    vi: Lập trình
description:
    en: "Unleashing the power of code: A journey into the world of programming."
    vi: "Khai phóng sức mạnh của mã nguồn: Chuyến đi vào thế giới lập trình."
icon: fas fa-code
