name: mpn

on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [ main ]
    paths: [ 'dosrc/**', '.github/workflows/mpn.yml' ]

  pull_request:
    branches: [ main ]
    types: [ closed ]

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.MPN_REGISTRY_USERNAME }}
          password: ${{ secrets.MPN_REGISTRY_PASSWORD }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: btnguyen2k/mpn:${{ github.sha }}
          file: ./Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MPN_AZURE_CREDENTIALS }}
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update \
              --subscription "${{ secrets.MPN_AZURE_SUBSCRIPTION_ID }}" \
              --name "mpn" \
              --resource-group "poc-auseast-rg" \
              --container-name "app" \
              --image "docker.io/btnguyen2k/mpn:${{ github.sha }}"
